version: '3.7'
services:
    web:
        build: .
        env_file:
          - .env
        environment:
            - SERVER_DSN=0.0.0.0:5000
        ports:
            - 5000:5000
        depends_on:
            - redisdb

    test:
        build: .
        command: go test ./...
        env_file:
            - .env

        depends_on:
            - redisdb

    redisdb:
        image: redis:7.0
