version: '3.7'
services:
    web:
        build: .
        env_file:
          - .env
        environment:
            - SERVER_DSN=0.0.0.0:5000
            - REDIS_PASS=the-stronge-one
            - REDIS_DNS=redisdb:6379
        ports:
            - 5000:5000
        depends_on:
            - redisdb

    test:
        build: .
        command: go test ./...
        env_file:
            - .env

        depends_on:
            - redisdb

    redisdb:
        image: redis:7.0
        environment:
        - ALLOW_EMPTY_PASSWORD=false 
        - REDIS_PASSWORD=the-stronge-one
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
        - '6379:6379'
